### ISSUE TITLE
Bot inicia mas não responde aos comandos

### ISSUE THREAD

**Issue by guuhzinho** [RootGC/JethJS#104]
Baixei a source, preenchi a .env mas ele não responde aos comandos, quando utilizo os slash da erro. Se puder ajudar :)

**Comment by Nikii-Discord** [comment]
O projeto foi temporariamente pausado após a vinda do Discord.js V14, por ter recebido diversos problemas relacionados a build do bot e até mesmo com o Discord. Peço que aguarde a retomada do projeto para solução do(s) problema(s).

**Comment by guuhzinho** [comment]
ok lindo, obrigado!
