### ISSUE TITLE
Bot não responde aos comandos

### ISSUE THREAD

**Issue by gustavomiauu** [RootGC/JethJS#107]
O bot liga, eu menciono e ele responde, mas não responde a nenhum comando.
![Screenshot_1](https://user-images.githubusercontent.com/118156028/201585245-8e80aaf3-5650-47b2-b2fb-5118f95875d7.png)

**Comment by solundev** [comment]
**Bom dia,**

Embora openSRC nosso projeto foi feito para responder em um bot já específico dentro do Discord, você pode baixar e tentar recriar em outro bot porém a falta de algumas dependências e outros podem causar erros como este.

Entretanto, se mesmo utilizando nossa **[interaction](https://discord.com/oauth2/authorize?client_id=936773967279173662&scope=bot+identify+guilds+guilds.join&permissions=1644905889015)** oficial este erro persistir, o issue pode ser reaberto.
