### ISSUE TITLE
Apenas membros confiáveis da equipe, o que isso significa?

### ISSUE THREAD

**Issue by josepaula** [RootGC/JethJS#122]
Estou recebendo o erro do titulo, o que posso fazer? Estou estudando o bot para o discord. quero programar algo parecido.

**Comment by solundev** [comment]
Boa noite, primeiramente desculpa a demora para responder... tenho estado afastado um pouco da equipe de desenvolvimento por várias razões.
Respondendo sua pergunta, alguns comandos criados são privados para que apenas os criadores ou membros de uma antiga seleta equipe nossa pudessem usar, entretanto todas estas configurações podem ser alteradas de certa forma, algumas precisam ser diretamente na database e outras pelo próprio src code.

Qualquer dúvida extra pode estar entrando em contato!
