### ISSUE TITLE
Mute não funcional?

### ISSUE THREAD

**Issue by solundev** [RootGC/JethJS#70]
Erro precisa ser identificado

![image](https://user-images.githubusercontent.com/82925878/158749024-fe675ebb-c576-405c-b0d0-fdc7d7a52053.png)

**Comment by Nikii-Discord** [comment]
_**Bugs in commands "Warn" and "Mute" in version Discord.JS V12**_ 

https://user-images.githubusercontent.com/100243657/158849943-f761c728-3ba6-4fa8-98ed-cc5eda182d1a.mp4

**Comment by solundev** [comment]
O Comando será retransformado dentro da próxima update, sendo assim o timeout deverá assumir seu lugar, funcionando de forma mais agradável e elegante juntamente ao sistema de buttons.
