### ISSUE TITLE
BlacklistCommand não reconhecendo blacklistModule

### ISSUE THREAD

**Issue by solundev** [RootGC/JethJS#84]
```js
C:\Users\mathe\OneDrive\Desktop\JethJS-13\src\commands\Magic\BlacklistCommand.js:79
          if (guildData.blacklistModule) {
                        ^

TypeError: Cannot read properties of null (reading 'blacklistModule')
    at C:\Users\mathe\OneDrive\Desktop\JethJS-13\src\commands\Magic\BlacklistCommand.js:79:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Nenhuma solução encontrada até o momento.

**Comment by solundev** [comment]
@DanielaGC **Not Fixed** erro continua e ainda pior, agora nenhum log é exibido dentro da Heroku ou CMD, comando não executando

**Comment by DanielaGC** [comment]
@SolarisGC vamos ver agora se foi corrigido ou não

**Comment by solundev** [comment]
> @SolarisGC vamos ver agora se foi corrigido ou não

negativo, ainda em aberto
![image](https://user-images.githubusercontent.com/82925878/169026514-4c5e651d-0c07-41b0-bf75-a26c82044ddd.png)
